// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9XctDxX53Q3GRyEuaR_a7VZNLleXf_R0',
    appId: '1:650599394858:web:952e298655e7638bbbdd53',
    messagingSenderId: '650599394858',
    projectId: 'checkinc-ff9b8',
    authDomain: 'checkinc-ff9b8.firebaseapp.com',
    storageBucket: 'checkinc-ff9b8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4hpd5zEcuiC5P4cQlJ32QuCQaUukrOkg',
    appId: '1:650599394858:android:41567891c6e8620cbbdd53',
    messagingSenderId: '650599394858',
    projectId: 'checkinc-ff9b8',
    storageBucket: 'checkinc-ff9b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPq7J_qnoz9829fztp_451WH-8foVt3b4',
    appId: '1:650599394858:ios:27f277d802fd3f23bbdd53',
    messagingSenderId: '650599394858',
    projectId: 'checkinc-ff9b8',
    storageBucket: 'checkinc-ff9b8.firebasestorage.app',
    iosBundleId: 'com.example.checkinc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPq7J_qnoz9829fztp_451WH-8foVt3b4',
    appId: '1:650599394858:ios:27f277d802fd3f23bbdd53',
    messagingSenderId: '650599394858',
    projectId: 'checkinc-ff9b8',
    storageBucket: 'checkinc-ff9b8.firebasestorage.app',
    iosBundleId: 'com.example.checkinc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9XctDxX53Q3GRyEuaR_a7VZNLleXf_R0',
    appId: '1:650599394858:web:e496a97887a3bef3bbdd53',
    messagingSenderId: '650599394858',
    projectId: 'checkinc-ff9b8',
    authDomain: 'checkinc-ff9b8.firebaseapp.com',
    storageBucket: 'checkinc-ff9b8.firebasestorage.app',
  );
}
